image: node:14.13.1

pages:
  cache:
    paths:
      - node_modules/

  stage: build
  script:
    - export REACT_APP_GA_ID=$REACT_APP_GA_ID

  stage: deploy
  variables:
    REACT_APP_GA_ID: $GA_ID
  script:
    - echo $CI_JOB_STAGE
    - echo $REACT_APP_GA_ID
    - printenv
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public

  only:
    - deploy
