image: node:14.13.1

variables:
  PUBLIC_URL: "/personal-site"

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - deploy
